language: node_js
node_js:
  - "stable"
addons:
  postgresql: "9.4"
services:
  - postgresql
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@6.9.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - npm run coveralls
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
